assignment1/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'goodbye' ,to: 'goodbye#index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

assignment1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

assignment1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

assignment1/app/controllers/goodbye_controller.rb
class GoodbyeController < ApplicationController
  def index
  end
end

assignment1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

assignment1/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment1/app/helpers/goodbye_helper.rb
module GoodbyeHelper
end

assignment1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

assignment1/app/views/goodbye/index.html.slim
h1 Good Bye World !
=link_to 'Home',root_path

assignment1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloROR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

assignment1/app/views/welcome/index.html.slim
h1 Hello World !

=link_to 'Good Bye',goodbye_path